package Assignment8;

import java.util.Random;
class SharedResource {
    int number;
    boolean hasNumber = false;
}
class Producer extends Thread {
    private SharedResource shared;
    private Random rand = new Random();
    public Producer(SharedResource shared) {
        this.shared = shared;
    }
    public void run() {
        for (int i = 0; i < 10; i++) {
            synchronized (shared) {
                while (shared.hasNumber) {
                    try {
                        shared.wait();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                shared.number = rand.nextInt(100) + 1;
                System.out.println("Number generated by Producer: " + shared.number);
                shared.hasNumber = true;
                shared.notify();
            }
        }
    }
}
class Consumer extends Thread {
    private SharedResource shared;
    private int evenCount = 0;
    public Consumer(SharedResource shared) {
        this.shared = shared;
    }
    public void run() {
        for (int i = 0; i < 10; i++) {
            synchronized (shared) {
                while (!shared.hasNumber) {
                    try {
                        shared.wait();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                if (shared.number % 2 == 0) {
                    evenCount++;
                }
                shared.hasNumber = false;
                shared.notify();
            }
        }
        System.out.println("Number even numbers received by Consumer: " + evenCount);
    }
}
public class Question12{
    public static void main(String[] args) {
        SharedResource shared = new SharedResource();
        Producer producer = new Producer(shared);
        Consumer consumer = new Consumer(shared);
        producer.start();
        consumer.start();
    }
}